### ISSUE TITLE
Enable configuration of external container registries for image storage

### ISSUE THREAD

**Issue by chalindukodikara** [openchoreo/openchoreo#189]
### Description

Allow users to configure and manage external container registries where container images built through OpenChoreo workflows can be pushed and pulled. 

This includes support for setting registry URLs, providing authentication credentials, and selecting which registry to use during the build and deployment process.

**Comment by chalindukodikara** [comment]
We are adopting the Kubernetes standard approach for handling images from private registries.

If users want to push built images to a private registry, they must first create a Kubernetes Secret of type kubernetes.io/dockerconfigjson ([reference](https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/)). This Secret should be created in the Control Plane cluster, under the organization's namespace, and will be referenced by the DataPlane kind.

When a build is triggered, the build controller:
- Identifies all the DataPlane instances associated with the relevant Deployment Pipeline of the component.
- Collects all referenced image push secrets from these DataPlanes.
- Combines them to create a consolidated dockerconfigjson Secret inside the choreo-ci namespace of the dataplane where the build runs.
- The file will be mounted to the push step pod. It will be used for pushing.

This dockerconfigjson contains the credentials necessary to push the built images to all configured private registries.

Once the build is complete:
- The workflow will push the built image to all Container Registries associated with the project's DataPlanes.
- This ensures that every relevant DataPlane can later pull the image successfully for deployments.

Additional details:
- A single DataPlane can be linked to multiple private registries.
- A single component can be associated with multiple DataPlanes.
- Therefore, an image may need to be pushed to multiple registries across multiple DataPlanes to guarantee availability at deployment time. This might be needed when doing promotions.

**Comment by chalindukodikara** [comment]
<img width="1424" alt="Image" src="https://github.com/user-attachments/assets/9cea78d8-a181-44eb-815f-f188069b6cac" />

**Comment by chalindukodikara** [comment]
DataPlane kind with push secrets.

```
apiVersion: core.choreo.dev/v1
kind: DataPlane
metadata:
  annotations:
    core.choreo.dev/description: Local development data plane
    core.choreo.dev/display-name: Default Data Plane
  labels:
    core.choreo.dev/name: default-dataplane
    core.choreo.dev/organization: default-org
  name: default-dataplane
  namespace: default-org
spec:
  registry:
    imagePushSecrets:
      - name: dev-dockerhub-push-secret
        prefix: docker.io/chalindukodikara
      - name: dev-ghcr-push-secret
        prefix: ghcr.io/your-org
  gateway:
    organizationVirtualHost: choreoapis.internal
    publicVirtualHost: choreoapis.localhost
  kubernetesCluster:
    credentials:
      apiServerURL: https://127.0.0.1:63846
      caCert: xxx
      clientCert: xxx
      clientKey: xxx
    name: kind-choreo-dp
```

**Comment by supekshala** [comment]
Happy to contrubite to this issue

**Comment by chalindukodikara** [comment]
> Happy to contrubite to this issue

Hi @supekshala, great to hear that!

**Comment by chalindukodikara** [comment]
### We've updated the user experience around handling container registry secrets to improve security and separation of concerns.
- Secrets are no longer created in the Control Plane.
- For each container registry that requires authentication, users must create a Kubernetes Secret in the Argo namespace. Argo Workflows can run in a separate namespace, either on a dedicated cluster or a DataPlane cluster.
- One secret is needed per registry.

#### Since secrets remain on the DataPlane, this reduces the risk of credential leakage and improves overall security posture.

###  Flow Summary

#### One-Time Setup:
- **Create Secrets:** Create registry authentication secrets in the Argo namespace on the DataPlane for each external container registry.
- **Configure DataPlane Kind:** Define or update DataPlane kinds in the Control Plane to reference the secrets.

#### On Build Trigger

- Identifies all relevant DataPlane instances linked to the component's DeploymentPipeline.
- Gathers image push secrets and unauthenticated registry prefixes from those DataPlanes.
- Mounts the secrets into the push step of the Argo workflow pod.
- Push Step: Tags and pushes the built image to all configured registries.

#### Post Build
- All specified container registries (authenticated or not) will receive the built image.
- This ensures that all DataPlanes involved in deployments can successfully pull the image later.

**Comment by chalindukodikara** [comment]
<img width="1064" alt="Image" src="https://github.com/user-attachments/assets/fff36346-f00c-452a-bc79-2aff82b1f856" />

**Comment by chalindukodikara** [comment]
Updated spec.

```
apiVersion: core.choreo.dev/v1
kind: DataPlane
metadata:
  annotations:
    core.choreo.dev/description: Local development data plane
    core.choreo.dev/display-name: Default Data Plane
  labels:
    core.choreo.dev/name: default-dataplane
    core.choreo.dev/organization: default-org
  name: default-dataplane
  namespace: default-org
spec:
  registry:
    unauthenticated:
      - docker.io/test
      - registry.choreo-system:5000
    imagePushSecrets:
      - name: dev-dockerhub-push-secret
        prefix: docker.io/your-org
      - name: dev-ghcr-push-secret
        prefix: ghcr.io/your-org
  gateway:
    organizationVirtualHost: choreoapis.internal
    publicVirtualHost: choreoapis.localhost
  kubernetesCluster:
    credentials:
      apiServerURL: https://127.0.0.1:63846
      caCert: xxx
      clientCert: xxx
      clientKey: xxx
    name: kind-choreo-dp
```

**Comment by sameerajayasoma** [comment]
We had an offline chat on this issue and discussed the following design. We decided to introduce another concept called BuildPlane, which runs Argo Workflows.

---

OpenChoreo uses a multi-plane architecture to model different responsibilities in a platform engineering setup. These planes represent logical roles in your internal developer platform and are typically mapped to Kubernetes clusters. Each plane is modeled explicitly via a custom resource (CR) in the control plane.

### Control Plane
The Control Plane is the core of the OpenChoreo platform. It hosts all system components responsible for managing developer intent and orchestrating deployments across environments. These components include the OpenChoreo Operator, API server and GitOps orchestrators like Argo CD. 

The control plane is responsible for interpreting high-level abstractions such as Projects, Components, Connections, and Environments, and translating them into concrete runtime configurations. 

It maintains the global state of the platform and coordinates interactions between planes. While it typically runs in its own Kubernetes cluster, it can also be colocated with a data or build plane in smaller setups (e.g., local development environments).

### Data Plane
The Data Plane is where application workloads are deployed and executed. These workloads may include microservices, APIs, scheduled jobs, and network gateways, all of which are orchestrated based on developer-defined configurations. Each data plane is backed by a single Kubernetes cluster and is modeled as a **DataPlane** CR in the control plane. 

OpenChoreo supports registering multiple data planes to represent different environments or geographic regions—for example, one for staging and another for production. 

### Build Plane
The Build Plane is responsible for running CI workflows such as building container images, running tests, and publishing artifacts. It is powered by Argo Workflows and operates in a Kubernetes cluster that is separate from both the control and data planes. 

Each build plane is registered via a BuildPlane CR, which provides the control plane with the necessary connection details to dispatch build jobs. Decoupling the build infrastructure from runtime environments allows for more effective resource isolation, security hardening, and scalability. 

This separation ensures that compute-intensive build jobs do not interfere with application runtime, and enables platform operators to manage build resources independently of deployment targets.

**Comment by chalindukodikara** [comment]
OpenChoreo follows a multi-plane architecture to separate concerns in a modern platform engineering setup. Currently, the `Control Plane` acts as the core of the OpenChoreo platform, managing developer intent and orchestrating deployments across environments. The `Data Plane` is responsible for running application workloads, and as of now, also executes build workflows. However, builds could and should be executed on any cluster, not just the data plane.

To accommodate this flexibility and align with our architecture, we are introducing a new resource called `BuildPlane`, which encapsulates all build-related configuration and responsibilities.

In addition, we require a `ContainerRegistry` Custom Resource (CR) to manage container image access credentials:
- Push secrets are used by the BuildPlane to push images to registries.
- Pull secrets are used by the DataPlane to retrieve images during deployment.

Introducing a dedicated `ContainerRegistry` CR allows for better separation of concerns and credential management.

**Comment by chalindukodikara** [comment]
<img width="430" alt="Image" src="https://github.com/user-attachments/assets/9b8d1ae3-3daf-4bdb-83ab-db7f02d45398" />

ER diagram for the build plane and related resources.

**Comment by chalindukodikara** [comment]
Related Resources.

```
apiVersion: core.openchoreo.dev
kind: DataPlane
metadata:
spec:
  # References to ContainerRegistry CRs used for pulling images.
  registries:
    - dev-docker
    - prod-ghcr
```

```
apiVersion: core.openchoreo.dev
kind: BuildPlane
metadata:
spec:
  # References to ContainerRegistry CRs used for image push operations.
  registries:
    - dev-docker
    - prod-ghcr
  kubernetesCluster:
    name: test-cluster
    credentials: 
      apiServerUrl: xxx
      caCert: xxx
      clientCert: xxx
      clientKey: xxx
```

```
apiVersion: core.openchoreo.dev
kind: ContainerRegistry
metadata:
spec:
    prefix: [ghcr.io/your-org](http://ghcr.io/your-org)
    authenticated: False (Default: True)
    imagePullSecret: prod-ghcr-pull-secret
    imagePushSecret: prod-ghcr-push-secret
```

**Comment by chalindukodikara** [comment]
We discussed the following challenges and arrived at the conclusions outlined below:

### 1. Supporting Multiple BuildPlanes per Organization

**Single BuildPlane per Organization**
In the simple case where an organization has only one BuildPlane, the system behaves predictably and without complexity. 

**Multiple BuildPlanes per Organization**
Some platform engineering (PE) teams may require multiple BuildPlanes within a single organization, for example, if different departments operate isolated clusters for their CI workloads.

However, this introduces the following challenges:

1. Should the build run on all BuildPlanes? Then, the image hash can be different.
2. Should it follow a round-robin or some other scheduling logic?
3. If the same build is run on multiple BuildPlanes, all of them must have access to the required push secrets for the relevant container registries. PEs should make sure, those are created.
4. Should another abstraction (such as the Project kind) explicitly reference the desired BuildPlane?

#### Conclusion
- BuildPlane and DataPlane operate independently.
- Each Component is associated with a single BuildPlane.
- While multiple BuildPlanes may exist within an organization, there must be a default BuildPlane at the organization level.
- This default can be overridden by the Project or future sub-organization constructs.
- Initial implementation will support only one BuildPlane per organization.
   - Support for multiple BuildPlanes will be added in later phases.

### 2. Identifying Relevant Container Registries for a Component
To determine where to push a built image, the system needs to identify the relevant container registries:
- The DeploymentPipeline references one or more DataPlane resources.
- Each DataPlane includes a list of container registry references.
- The Build Controller computes the union of all referenced registries from these DataPlanes.
- It then compares this union with the list of registries configured in the selected BuildPlane:
   - If a registry is not listed in the BuildPlane and requires authentication, it is excluded from the push target list.
   - The remaining registries (i.e., public and authenticated) are used as the targets for image pushes.


#### Conclusion
- BuildPlane controls the actual image push targets.
- The image is pushed to all registries listed in the BuildPlane, even if some are not associated with the specific component.

**Advantages:**
Enables future promotion scenarios: If a new environment is added to the DeploymentPipeline later, image promotion works without re-triggering the build, since the image already exists in the relevant registry.


**Disadvantages:**
Wasted storage: Images are pushed to registries that may not be used by the component, potentially leading to unnecessary storage usage.

**Comment by chalindukodikara** [comment]
## External Registry Support (without BuildPlane Kind)
The external registry feature is currently implemented without the `BuildPlane` kind [1]. Platform Engineers (PEs) can configure both `authenticated` and `unauthenticated` container registries directly within the `DataPlane` resources. These registries define where built images will be pushed.

Support for a dedicated `BuildPlane` kind is on the roadmap and will be introduced in a future release.

[1] https://github.com/openchoreo/openchoreo/pull/213

## Configuring Unauthenticated Registries

If the container registry does **not require authentication** (e.g., public repositories), it is required to declare them in the corresponding DataPlane custom resource.

### Example Configuration

Add the following to your `DataPlane` CR:

```yaml
spec:
  registry:
    unauthenticated:
      - docker.io/<your-org>
      - ghcr.io/<your-org>
      - registry.choreo-system:5000
```

## Configuring Authenticated Registries

To push images to **private registries**, it is required to set up secrets in the Build Plane and link them from the appropriate DataPlanes.

#### 1. Create Image Push Secrets

Create Kubernetes secrets for the private registries in the **BuildPlane's** namespace:

- Namespace: `choreo-ci-<org-name>`

#### 2. Reference Secrets in the DataPlane

Push secrets should be added to DataPlane CR as follows:

```yaml
spec:
  registry:
    imagePushSecrets:
      - name: dev-dockerhub-push-secret
        prefix: docker.io/<your-org>
      - name: prod-ghcr-push-secret
        prefix: ghcr.io/<your-org>
```
