### ISSUE TITLE
The `openchoreo.yaml` – Declarative specification for OpenChoreo abstractions

### ISSUE THREAD

**Issue by sameerajayasoma** [openchoreo/openchoreo#199]
With OpenChoreo, developers use the following abstractions to manage their work. These abstractions align with the Domain-Driven Design principles, where projects represent bounded contexts and components represent the individual services or workloads within a domain. Developers use these abstractions to describe the structure and intent of the application in a declarative manner without having to deal with runtime infrastructure details.

- **Projects** are cloud-native applications composed of multiple components. Serves as the unit of isolation. It's similar to the concept of Application or System in other platforms. 
- **Components** are deployable units within a project, such as web apps,  services, or tasks.
- **Endpoints** are network-accessible interfaces exposed by a component, including routing rules, supported protocols, and visibility scopes (e.g., public, organization, project).
- **Connections** are outbound service dependencies defined by a component, targeting either other components or external systems.

What problem are we trying to solve with `openchoreo.yaml`?
In the current model, OpenChoreo expects developers to write multiple CRs or use OpenChoreo CLI to create them by invoking multiple commands. 
- Developers need to write or generate around 4 CRDs: Component, DeploymentTrack, DeployableArtifact and Deployment. 
- Each required repeated labels, metadata and namespace. 
- It's easy to get wrong with repeated labels. 
- Tightly coupled to platform-specific concepts and exposes too much infra detail.

The `openchoreo.yaml`
We can introduce a developer-friendly way of declaring the intent of their component, project, etc., in a YAML file.  The aim is to simplify how developers define and deploy their stuff in OpenChoreo. 
- Developers can maintain this file along with their application source code.
- Single source of truth for the component, project, etc.
- Removes the need to create multiple low-level CRDs. 

We'll publish a complete spec for `openchoreo.yaml` soon. The purpose of this issue is to announce this plan. 

Here is a sample `openchoreo.yaml` that describes a Component and an API
```yaml
apiVersion: choreo.dev/v1alpha1
kind: Component
metadata:
  name: reading-list
  project: reading-list-project
spec:
  runtime:
    image: ghcr.io/org/reading-list:main

  endpoints:
    - name: reading-list
       type: TCP
       port: 8080

  connections:
    - name: book-service
       resourceRef: ...
    - name: reading-list-db 
       resourceRef: ....	

--
apiVersion: choreo.dev/v1alpha1
kind: API
metadata:
  name: reading-list-api
  component: reading-list
  project: reading-list-project
spec: 
  ...
```

`openchoreo.yaml` to OpenChoreo CR generation
The primary goal of the OpenChoreo control plane, working in conjunction with CI pipelines (such as Argo Workflows or GitHub Actions), is to translate developer intent into running workloads across one or more OpenChoreo data planes.

OpenChoreo control plane can expose an endpoint for component deployment. CI pipelines can use this endpoint to deploy a component with the new image and `openchoreo.yaml`.
