### ISSUE TITLE
`openchoreo.yaml` spec for API management configurations

### ISSUE THREAD

**Issue by VajiraPrabuddhaka** [openchoreo/openchoreo#212]
## Description

With the introduction of [`openchoreo.yaml`](https://github.com/openchoreo/openchoreo/issues/199), it is required to have a section for specifying the API management configurations for the APIs exposed by the components.

Here is the initially suggested spec.

```yaml
apiVersion: choreo.dev/v1alpha1
kind: Component
metadata:
  name: book-store
  project: book-store-project
spec:
  runtime:
    image: ghcr.io/org/book-store:main

  endpoints:
    - name: book-store
       type: TCP
       port: 8080

  connections:
    - name: book-service
       resourceRef: ...
    - name: book-service-db 
       resourceRef: ....	

--
apiVersion: choreo.dev/v1alpha1
kind: API
metadata:
  name: book-store-api
  component: book-store
  project: book-store-project
spec:
  type: REST
  backendRef:
    basePath: /api/v1/book-store
    type: componentRef  # or "target"
    componentRef:
      port: 8080
    target:
      url: https://run.mocky.io/v3/45bdb253-7eee-4db4-93dc-0c6b4beef8d2
  schema:
    filePath: openapi.yaml
  networkVisibilities:
    public:
      policies:
        - name: my-api-key-auth-policy
          type: apiKeyAuth
          policySpec:
            keySource:
              header: "X-API-Key"
              headerAuthScheme: "Bearer"  # Optional, depending on your needs
            secretValues:
              - api-key-secret-1
              - api-key-secret-2
        - name: my-basic-auth-policy
          type: basicAuth
          policySpec:
            users:
              - username: user1
                passwordFromSecret: secret-user1
              - username: user2
                passwordFromSecret: secret-user2
            header: "Authorization"
            headerAuthScheme: "Basic"
        - name: my-oauth2-policy
          type: oauth2
          policySpec:
            jwt:
              authorization:
                apiType: "REST"  # REST, GRPC, GraphQL
                # array of claims to be validated
                claims:
                  - key: aud
                    values: [ "choreo:books:api" ]
                claimsToHeaders:
                  - name: aud
                    header: x-aud
                operations: # array of operations
                  # There should be validations based on the type of the endpoint
                  # if the type is REST
                  - target: /books
                    method: GET
                    scopes: [ "api:read" ]
                  - target: /books
                    method: POST
                    scopes: [ "api:read", "api:write" ]
                  # if the type is GRPC
                  - name: BooksService
                    methods:
                      - name: AddBook
                        scopes: [ "grpc:read", "grpc:write" ]
                  # if the type is GraphQL
                  - type: query
                    name: books
                    scopes: [ "api:read" ]
        - name: my-rate-limit-policy
          type: rateLimit
          policySpec:
            apiLevel:
              timeUnit: "minute"
              requestLimit: 100  # -1 for unlimited
            operationLevel:
              rest:
                operations:
                  - target: "/books"
                    method: "GET"
                    timeUnit: "minute"
                    requestLimit: 50
                  - target: "/books"
                    method: "POST"
                    timeUnit: "hour"
                    requestLimit: 20
        - name: my-cors-policy
          type: cors
          policySpec:
            allowOrigins:
              - "*"  # Or specific origins like "https://example.com"
            allowMethods:
              - "GET"
              - "POST"
              - "PUT"
              - "DELETE"
            allowHeaders:
              - "Content-Type"
              - "Authorization"
            exposeHeaders:
              - "X-Custom-Header"
            maxAge: 3600
            allowCredentials: false
        - name: my-mediation-policy
          type: mediation
          enabled: true
          policySpec:
            requestFlow:
              - action: "addHeader"
                parameters:
                  name: "X-Tracking-ID"
                  value: "${request.id}"
              - action: "transformBody"
                parameters:
                  template: |
                    {
                      "transformedRequest": ${request.body}
                    }
            responseFlow:
              - action: "addHeader"
                parameters:
                  name: "X-Response-Time"
                  value: "${context.elapsedTime}"
              - action: "filterHeaders"
                parameters:
                  remove:
                    - "Server"
                    - "X-Powered-By"
    organization:
      settings:
        policies:
          - name: my-api-key-auth-policy
            type: apiKeyAuth
            policySpec: {}
          - name: my-rate-limit-policy
            type: rateLimit
            policySpec: {}
          - name: my-cors-policy
            type: cors
            policySpec: {}
          - name: my-mediation-policy
            type: mediation
            policySpec: {}
```
