### ISSUE TITLE
Add support to run Argo Workflows in any Data Plane cluster

### ISSUE THREAD

**Issue by chalindukodikara** [openchoreo/openchoreo#217]
### Description
Currently, Argo Workflows are executed on a hardcoded Data Plane (default-dataplane). This behavior should be made configurable to support execution on different Data Planes based on user input.

Allowing builds to run on any specified cluster offers users more control over their CI/CD pipelines. This infrastructure separation is required for governance or scalability reasons.

### Related Issues
https://github.com/openchoreo/openchoreo/issues/189

**Comment by chalindukodikara** [comment]
OpenChoreo follows a multi-plane architecture to separate concerns in a modern platform engineering setup. Currently, the `Control Plane` acts as the core of the OpenChoreo platform, managing developer intent and orchestrating deployments across environments. The `Data Plane` is responsible for running application workloads, and as of now, also executes build workflows. However, builds could and should be executed on any cluster, not just the data plane.

To accommodate this flexibility and align with our architecture, we are introducing a new resource called `BuildPlane`, which encapsulates all build-related configuration and responsibilities.

Refer https://github.com/openchoreo/openchoreo/issues/189 for more details.

**Comment by chalindukodikara** [comment]
<img width="430" alt="Image" src="https://github.com/user-attachments/assets/a9ca247b-0687-4ba5-8e5a-5f3f4b0d350a" />

ER diagram for the build plane and related resources.

**Comment by chalindukodikara** [comment]
BuildPlane kind.

```
apiVersion: core.choreo.dev
kind: BuildPlane
metadata:
spec:
  # References to ContainerRegistry CRs used for image push operations.
  registries:
    - dev-docker
    - prod-ghcr
  kubernetesCluster:
    name: test-cluster
    credentials: 
      apiServerUrl: xxx
      caCert: xxx
      clientCert: xxx
      clientKey: xxx
```
